complete -c dot -f
complete -c dot -s v -l verbose -d 'Print verbose progress diagnostics'
complete -c dot -s h -l help -d 'Show help'
complete -c dot -l version -d 'Show version'

complete -c dot -n '__fish_use_subcommand' -a init -d 'Initialize and install dotfiles'
complete -c dot -n '__fish_use_subcommand' -a update -d 'Update dotfiles and packages'
complete -c dot -n '__fish_use_subcommand' -a doctor -d 'Run diagnostics'
complete -c dot -n '__fish_use_subcommand' -a info -d 'Show repository and runtime info'
complete -c dot -n '__fish_use_subcommand' -a hooks -d 'Install repository Git hooks'
complete -c dot -n '__fish_use_subcommand' -a secret-scan -d 'Scan repository for secrets'
complete -c dot -n '__fish_use_subcommand' -a package -d 'Manage Homebrew bundle packages'
complete -c dot -n '__fish_use_subcommand' -a skills -d 'Manage shared global Agent Skills'
complete -c dot -n '__fish_use_subcommand' -a config -d 'Manage local-only preferences'
complete -c dot -n '__fish_use_subcommand' -a git-identity -d 'Create or update local Git identity'
complete -c dot -n '__fish_use_subcommand' -a stow -d 'Create symlinks using GNU Stow'
complete -c dot -n '__fish_use_subcommand' -a unstow -d 'Remove stowed symlinks'
complete -c dot -n '__fish_use_subcommand' -a help -d 'Show help'

complete -c dot -n '__fish_seen_subcommand_from package' -a 'list check unmanaged trusted untrusted add remove update retry help' -d 'Package command'
complete -c dot -n '__fish_seen_subcommand_from skills' -a 'add list help' -d 'Skills command'
complete -c dot -n '__fish_seen_subcommand_from config' -a 'list get set unset reset help' -d 'Config command'
