minimumReleaseAge: 7200
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@opencode/cli'
  - '@opencode/cli-*'
  - '@opencode/*'
dangerouslyAllowAllBuilds: false
globalShims:
  node: auto
  deno: auto
  bun: auto
  npm: auto
